distance: 1.5
teleport-on-start: false
teleport-with-direction: true
remember-on-logout: true

checkpoints:
  start:
    block: DIAMOND_BLOCK
    text:
      - "&aParkour {parkour} &2Start"
      #- "&aBest time: &2{best}"
  checkpoint:
    block: GOLD_BLOCK
    text:
      - "&aCheckpoint &6#{checkpoint}"
  end:
    block: EMERALD_BLOCK
    text:
      - "&aParkour {parkour} &cEnd!"

items:
  restart:
    name: "&cReset"
    material: OAK_DOOR
    slot: 4
    commands:
      - parkour reset
  checkpoint:
    name: "&aTeleport to the Last Checkpoint"
    material: HEAVY_WEIGHTED_PRESSURE_PLATE
    slot: 3
    commands:
      - parkour checkpoint
  stop:
    name: "&cCancel"
    material: RED_BED
    slot: 5
    commands:
      - parkour stop